### ISSUE TITLE
Example website generation parameters?

### ISSUE THREAD

**Issue by RichardScottOZ** [davendw49/k2#10]
For your example, it would be interesting to know what parameters you have set for generation for each query if they are the same, to compare?

e.g. I have some different or failures with the defaults.

**Comment by RichardScottOZ** [comment]
Other difference I guess could be the particular Llama 7B applied to the delta?

**Comment by RichardScottOZ** [comment]
Are you using one that you applied for from Meta/Hugging Face - or something else?

**Comment by RichardScottOZ** [comment]
Also, FYI

https://github.com/RichardScottOZ/k2/tree/main/generation

https://github.com/CalculatedContent/WeightWatcher/tree/master

**Comment by davendw49** [comment]
> Other difference I guess could be the particular Llama 7B applied to the delta?

Despite of further pretraining, we also use LoRA to supervised fine-tuneon via GeoSignal. Consequently, we should adapt the delta weights and add up the [adapter weights](https://huggingface.co/daven3/k2_it_adapter).

**Comment by RichardScottOZ** [comment]
Yeah, am looking at that - and the generic Llama base model I used.  I will upload those.

**Comment by RichardScottOZ** [comment]
I have added delta = k2_fp_delta and the base llama

**Comment by davendw49** [comment]
Then you should use adapter model to do the generation, here is the parameters we have set for generation:
```python
generation_config = GenerationConfig(
    temperature=0.1,
    top_p=0.75,
    top_k=40,
    num_beams=4,
    no_repeat_ngram_size=2,
    max_length=1000,
)
```
and we set a [`stopping criteria`](https://huggingface.co/docs/transformers/internal/generation_utils#transformers.StoppingCriteria) for online application, which we consider it as an engineering subject.
