### ISSUE TITLE
🆘 I need the geosignal.json dataset for finetunning. 

### ISSUE THREAD

**Issue by Chowhound-G** [davendw49/k2#16]
The amount of data translated is too large. Are there any Chinese version of geosignal.json? 
Badly in need of need the Chinese version of the dataset. 
It doesn't matter if it doesn't.
Sorry to take up the issue. Thanks a lot.🙏

**Comment by davendw49** [comment]
As a scientific exploration, we didn't preserve any Chinese version, sorry!

**Comment by Chowhound-G** [comment]
Thank you very much for receiving the reply. 
I have converted it through the translation API.

**Comment by Chowhound-G** [comment]
> As a scientific exploration, we didn't preserve any Chinese version, sorry!


Thank you very much for receiving the reply.
I have converted it through the translation API.
